#! /bin/bash
set -e

source /home/ws/.script/envinit.bash

if [ -z "${RMCS_ROBOT_TYPE}" ]; then
    echo "Error: Please set robot first."
    exit 1
fi

echo "Starting RMCS robot=${RMCS_ROBOT_TYPE} with servo USB protocol and diagnostics"
ros2 launch atrm_bringup rmcs.launch.py robot:=${RMCS_ROBOT_TYPE}
